name: Docker Build - DICOMn

on:
  push:
    branches: [ "main", "dev" ]
    pull_request:
      branches: [ "main", "dev" ]

jobs:
  docker-build-image:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS Credentials
        uses: amazon/aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2
      - uses: actions/checkout@v3
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
      - name: Build the Docker image for DICOMn
        working-directory: ./
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: DICOMn
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build . -t $REGISTRY/$REPOSITORY:$IMAGE_TAG
          docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG