name: ci

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Login to Docker Hub # this should be changed to AWS
        uses: docker/login-action@v3 # aws-actions/configure-aws-credentials@v1
        with:
          username: ${{ vars.DOCKER_USERNAME }} # ${{ secrets.AWS_ACCESS_KEY_ID }}
          password: ${{ secrets.DOCKERHUB_TOKEN }} # ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          # aws-region: us-west-2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64  # Adjust platforms if needed
          push: true
          tags: ${{ vars.DOCKER_USERNAME }}/${{ github.event.repository.name }}:latest
